export const climbingRoutes = [
    {
        id: 'r1',
        name: 'La Demande (Verdon Gorge, France)',
        difficulty: '6a',
        outingsBooked: true,
        averageRating: 4.9,
        category: 'advanced',
    },
    {
        id: 'r2',
        name: 'Via Ferrata delle Bocchette (Dolomites, Italy)',
        difficulty: '5a',
        outingsBooked: true,
        averageRating: 4.7,
        category: 'beginner',
    },
    {
        id: 'r3',
        name: 'Zulù Demente (Margalef, Spain)',
        difficulty: '8b+',
        outingsBooked: false,
        averageRating: 4.9,
        category: 'pro',
    },
    {
        id: 'r4',
        name: 'Super Weissmies (Saas Valley, Switzerland)',
        difficulty: '6b',
        outingsBooked: false,
        averageRating: 4.5,
        category: 'intermediate',
    },
    {
        id: 'r5',
        name: 'Les Dalles Grises (Aiguilles Rouges, France)',
        difficulty: '5c',
        outingsBooked: true,
        averageRating: 4.6,
        category: 'beginner',
    },
    {
        id: 'r6',
        name: 'Hubble Bubble (Kalymnos, Greece)',
        difficulty: '7a',
        outingsBooked: true,
        averageRating: 4.8,
        category: 'advanced',
    },
    {
        id: 'r7',
        name: 'Action Directe (Frankenjura, Germany)',
        difficulty: '9a',
        outingsBooked: false,
        averageRating: 5.0,
        category: 'pro',
    },
    {
        id: 'r8',
        name: 'Les Chéserys Traverse (Chamonix, France)',
        difficulty: '5b',
        outingsBooked: true,
        averageRating: 4.4,
        category: 'beginner',
    },
    {
        id: 'r9',
        name: 'Fish Route (Dolomites, Italy)',
        difficulty: '7c',
        outingsBooked: true,
        averageRating: 4.9,
        category: 'pro',
    },
    {
        id: 'r10',
        name: 'El Delfín (Rodellar, Spain)',
        difficulty: '8a',
        outingsBooked: false,
        averageRating: 4.8,
        category: 'pro',
    },
];
